//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	v1alpha1 "k8s.io/api/networking/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
	core "k8s.io/kubernetes/pkg/apis/core"
	networking "k8s.io/kubernetes/pkg/apis/networking"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ClusterCIDR)(nil), (*networking.ClusterCIDR)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterCIDR_To_networking_ClusterCIDR(a.(*v1alpha1.ClusterCIDR), b.(*networking.ClusterCIDR), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.ClusterCIDR)(nil), (*v1alpha1.ClusterCIDR)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_ClusterCIDR_To_v1alpha1_ClusterCIDR(a.(*networking.ClusterCIDR), b.(*v1alpha1.ClusterCIDR), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ClusterCIDRList)(nil), (*networking.ClusterCIDRList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterCIDRList_To_networking_ClusterCIDRList(a.(*v1alpha1.ClusterCIDRList), b.(*networking.ClusterCIDRList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.ClusterCIDRList)(nil), (*v1alpha1.ClusterCIDRList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_ClusterCIDRList_To_v1alpha1_ClusterCIDRList(a.(*networking.ClusterCIDRList), b.(*v1alpha1.ClusterCIDRList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ClusterCIDRSpec)(nil), (*networking.ClusterCIDRSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterCIDRSpec_To_networking_ClusterCIDRSpec(a.(*v1alpha1.ClusterCIDRSpec), b.(*networking.ClusterCIDRSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.ClusterCIDRSpec)(nil), (*v1alpha1.ClusterCIDRSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_ClusterCIDRSpec_To_v1alpha1_ClusterCIDRSpec(a.(*networking.ClusterCIDRSpec), b.(*v1alpha1.ClusterCIDRSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.IPAddress)(nil), (*networking.IPAddress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPAddress_To_networking_IPAddress(a.(*v1alpha1.IPAddress), b.(*networking.IPAddress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.IPAddress)(nil), (*v1alpha1.IPAddress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_IPAddress_To_v1alpha1_IPAddress(a.(*networking.IPAddress), b.(*v1alpha1.IPAddress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.IPAddressList)(nil), (*networking.IPAddressList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPAddressList_To_networking_IPAddressList(a.(*v1alpha1.IPAddressList), b.(*networking.IPAddressList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.IPAddressList)(nil), (*v1alpha1.IPAddressList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_IPAddressList_To_v1alpha1_IPAddressList(a.(*networking.IPAddressList), b.(*v1alpha1.IPAddressList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.IPAddressSpec)(nil), (*networking.IPAddressSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPAddressSpec_To_networking_IPAddressSpec(a.(*v1alpha1.IPAddressSpec), b.(*networking.IPAddressSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.IPAddressSpec)(nil), (*v1alpha1.IPAddressSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_IPAddressSpec_To_v1alpha1_IPAddressSpec(a.(*networking.IPAddressSpec), b.(*v1alpha1.IPAddressSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ParametersRef)(nil), (*networking.ParametersRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ParametersRef_To_networking_ParametersRef(a.(*v1alpha1.ParametersRef), b.(*networking.ParametersRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.ParametersRef)(nil), (*v1alpha1.ParametersRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_ParametersRef_To_v1alpha1_ParametersRef(a.(*networking.ParametersRef), b.(*v1alpha1.ParametersRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ParentReference)(nil), (*networking.ParentReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ParentReference_To_networking_ParentReference(a.(*v1alpha1.ParentReference), b.(*networking.ParentReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.ParentReference)(nil), (*v1alpha1.ParentReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_ParentReference_To_v1alpha1_ParentReference(a.(*networking.ParentReference), b.(*v1alpha1.ParentReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PodNetwork)(nil), (*networking.PodNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PodNetwork_To_networking_PodNetwork(a.(*v1alpha1.PodNetwork), b.(*networking.PodNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.PodNetwork)(nil), (*v1alpha1.PodNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_PodNetwork_To_v1alpha1_PodNetwork(a.(*networking.PodNetwork), b.(*v1alpha1.PodNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PodNetworkAttachment)(nil), (*networking.PodNetworkAttachment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PodNetworkAttachment_To_networking_PodNetworkAttachment(a.(*v1alpha1.PodNetworkAttachment), b.(*networking.PodNetworkAttachment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.PodNetworkAttachment)(nil), (*v1alpha1.PodNetworkAttachment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_PodNetworkAttachment_To_v1alpha1_PodNetworkAttachment(a.(*networking.PodNetworkAttachment), b.(*v1alpha1.PodNetworkAttachment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PodNetworkAttachmentList)(nil), (*networking.PodNetworkAttachmentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PodNetworkAttachmentList_To_networking_PodNetworkAttachmentList(a.(*v1alpha1.PodNetworkAttachmentList), b.(*networking.PodNetworkAttachmentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.PodNetworkAttachmentList)(nil), (*v1alpha1.PodNetworkAttachmentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_PodNetworkAttachmentList_To_v1alpha1_PodNetworkAttachmentList(a.(*networking.PodNetworkAttachmentList), b.(*v1alpha1.PodNetworkAttachmentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PodNetworkAttachmentSpec)(nil), (*networking.PodNetworkAttachmentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PodNetworkAttachmentSpec_To_networking_PodNetworkAttachmentSpec(a.(*v1alpha1.PodNetworkAttachmentSpec), b.(*networking.PodNetworkAttachmentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.PodNetworkAttachmentSpec)(nil), (*v1alpha1.PodNetworkAttachmentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_PodNetworkAttachmentSpec_To_v1alpha1_PodNetworkAttachmentSpec(a.(*networking.PodNetworkAttachmentSpec), b.(*v1alpha1.PodNetworkAttachmentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PodNetworkAttachmentStatus)(nil), (*networking.PodNetworkAttachmentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PodNetworkAttachmentStatus_To_networking_PodNetworkAttachmentStatus(a.(*v1alpha1.PodNetworkAttachmentStatus), b.(*networking.PodNetworkAttachmentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.PodNetworkAttachmentStatus)(nil), (*v1alpha1.PodNetworkAttachmentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_PodNetworkAttachmentStatus_To_v1alpha1_PodNetworkAttachmentStatus(a.(*networking.PodNetworkAttachmentStatus), b.(*v1alpha1.PodNetworkAttachmentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PodNetworkList)(nil), (*networking.PodNetworkList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PodNetworkList_To_networking_PodNetworkList(a.(*v1alpha1.PodNetworkList), b.(*networking.PodNetworkList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.PodNetworkList)(nil), (*v1alpha1.PodNetworkList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_PodNetworkList_To_v1alpha1_PodNetworkList(a.(*networking.PodNetworkList), b.(*v1alpha1.PodNetworkList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PodNetworkSpec)(nil), (*networking.PodNetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PodNetworkSpec_To_networking_PodNetworkSpec(a.(*v1alpha1.PodNetworkSpec), b.(*networking.PodNetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.PodNetworkSpec)(nil), (*v1alpha1.PodNetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_PodNetworkSpec_To_v1alpha1_PodNetworkSpec(a.(*networking.PodNetworkSpec), b.(*v1alpha1.PodNetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PodNetworkStatus)(nil), (*networking.PodNetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PodNetworkStatus_To_networking_PodNetworkStatus(a.(*v1alpha1.PodNetworkStatus), b.(*networking.PodNetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*networking.PodNetworkStatus)(nil), (*v1alpha1.PodNetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_networking_PodNetworkStatus_To_v1alpha1_PodNetworkStatus(a.(*networking.PodNetworkStatus), b.(*v1alpha1.PodNetworkStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ClusterCIDR_To_networking_ClusterCIDR(in *v1alpha1.ClusterCIDR, out *networking.ClusterCIDR, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterCIDRSpec_To_networking_ClusterCIDRSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterCIDR_To_networking_ClusterCIDR is an autogenerated conversion function.
func Convert_v1alpha1_ClusterCIDR_To_networking_ClusterCIDR(in *v1alpha1.ClusterCIDR, out *networking.ClusterCIDR, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterCIDR_To_networking_ClusterCIDR(in, out, s)
}

func autoConvert_networking_ClusterCIDR_To_v1alpha1_ClusterCIDR(in *networking.ClusterCIDR, out *v1alpha1.ClusterCIDR, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_networking_ClusterCIDRSpec_To_v1alpha1_ClusterCIDRSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_networking_ClusterCIDR_To_v1alpha1_ClusterCIDR is an autogenerated conversion function.
func Convert_networking_ClusterCIDR_To_v1alpha1_ClusterCIDR(in *networking.ClusterCIDR, out *v1alpha1.ClusterCIDR, s conversion.Scope) error {
	return autoConvert_networking_ClusterCIDR_To_v1alpha1_ClusterCIDR(in, out, s)
}

func autoConvert_v1alpha1_ClusterCIDRList_To_networking_ClusterCIDRList(in *v1alpha1.ClusterCIDRList, out *networking.ClusterCIDRList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]networking.ClusterCIDR)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterCIDRList_To_networking_ClusterCIDRList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterCIDRList_To_networking_ClusterCIDRList(in *v1alpha1.ClusterCIDRList, out *networking.ClusterCIDRList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterCIDRList_To_networking_ClusterCIDRList(in, out, s)
}

func autoConvert_networking_ClusterCIDRList_To_v1alpha1_ClusterCIDRList(in *networking.ClusterCIDRList, out *v1alpha1.ClusterCIDRList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.ClusterCIDR)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_networking_ClusterCIDRList_To_v1alpha1_ClusterCIDRList is an autogenerated conversion function.
func Convert_networking_ClusterCIDRList_To_v1alpha1_ClusterCIDRList(in *networking.ClusterCIDRList, out *v1alpha1.ClusterCIDRList, s conversion.Scope) error {
	return autoConvert_networking_ClusterCIDRList_To_v1alpha1_ClusterCIDRList(in, out, s)
}

func autoConvert_v1alpha1_ClusterCIDRSpec_To_networking_ClusterCIDRSpec(in *v1alpha1.ClusterCIDRSpec, out *networking.ClusterCIDRSpec, s conversion.Scope) error {
	out.NodeSelector = (*core.NodeSelector)(unsafe.Pointer(in.NodeSelector))
	out.PerNodeHostBits = in.PerNodeHostBits
	out.IPv4 = in.IPv4
	out.IPv6 = in.IPv6
	return nil
}

// Convert_v1alpha1_ClusterCIDRSpec_To_networking_ClusterCIDRSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterCIDRSpec_To_networking_ClusterCIDRSpec(in *v1alpha1.ClusterCIDRSpec, out *networking.ClusterCIDRSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterCIDRSpec_To_networking_ClusterCIDRSpec(in, out, s)
}

func autoConvert_networking_ClusterCIDRSpec_To_v1alpha1_ClusterCIDRSpec(in *networking.ClusterCIDRSpec, out *v1alpha1.ClusterCIDRSpec, s conversion.Scope) error {
	out.NodeSelector = (*v1.NodeSelector)(unsafe.Pointer(in.NodeSelector))
	out.PerNodeHostBits = in.PerNodeHostBits
	out.IPv4 = in.IPv4
	out.IPv6 = in.IPv6
	return nil
}

// Convert_networking_ClusterCIDRSpec_To_v1alpha1_ClusterCIDRSpec is an autogenerated conversion function.
func Convert_networking_ClusterCIDRSpec_To_v1alpha1_ClusterCIDRSpec(in *networking.ClusterCIDRSpec, out *v1alpha1.ClusterCIDRSpec, s conversion.Scope) error {
	return autoConvert_networking_ClusterCIDRSpec_To_v1alpha1_ClusterCIDRSpec(in, out, s)
}

func autoConvert_v1alpha1_IPAddress_To_networking_IPAddress(in *v1alpha1.IPAddress, out *networking.IPAddress, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_IPAddressSpec_To_networking_IPAddressSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_IPAddress_To_networking_IPAddress is an autogenerated conversion function.
func Convert_v1alpha1_IPAddress_To_networking_IPAddress(in *v1alpha1.IPAddress, out *networking.IPAddress, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPAddress_To_networking_IPAddress(in, out, s)
}

func autoConvert_networking_IPAddress_To_v1alpha1_IPAddress(in *networking.IPAddress, out *v1alpha1.IPAddress, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_networking_IPAddressSpec_To_v1alpha1_IPAddressSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_networking_IPAddress_To_v1alpha1_IPAddress is an autogenerated conversion function.
func Convert_networking_IPAddress_To_v1alpha1_IPAddress(in *networking.IPAddress, out *v1alpha1.IPAddress, s conversion.Scope) error {
	return autoConvert_networking_IPAddress_To_v1alpha1_IPAddress(in, out, s)
}

func autoConvert_v1alpha1_IPAddressList_To_networking_IPAddressList(in *v1alpha1.IPAddressList, out *networking.IPAddressList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]networking.IPAddress)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_IPAddressList_To_networking_IPAddressList is an autogenerated conversion function.
func Convert_v1alpha1_IPAddressList_To_networking_IPAddressList(in *v1alpha1.IPAddressList, out *networking.IPAddressList, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPAddressList_To_networking_IPAddressList(in, out, s)
}

func autoConvert_networking_IPAddressList_To_v1alpha1_IPAddressList(in *networking.IPAddressList, out *v1alpha1.IPAddressList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.IPAddress)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_networking_IPAddressList_To_v1alpha1_IPAddressList is an autogenerated conversion function.
func Convert_networking_IPAddressList_To_v1alpha1_IPAddressList(in *networking.IPAddressList, out *v1alpha1.IPAddressList, s conversion.Scope) error {
	return autoConvert_networking_IPAddressList_To_v1alpha1_IPAddressList(in, out, s)
}

func autoConvert_v1alpha1_IPAddressSpec_To_networking_IPAddressSpec(in *v1alpha1.IPAddressSpec, out *networking.IPAddressSpec, s conversion.Scope) error {
	out.ParentRef = (*networking.ParentReference)(unsafe.Pointer(in.ParentRef))
	return nil
}

// Convert_v1alpha1_IPAddressSpec_To_networking_IPAddressSpec is an autogenerated conversion function.
func Convert_v1alpha1_IPAddressSpec_To_networking_IPAddressSpec(in *v1alpha1.IPAddressSpec, out *networking.IPAddressSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPAddressSpec_To_networking_IPAddressSpec(in, out, s)
}

func autoConvert_networking_IPAddressSpec_To_v1alpha1_IPAddressSpec(in *networking.IPAddressSpec, out *v1alpha1.IPAddressSpec, s conversion.Scope) error {
	out.ParentRef = (*v1alpha1.ParentReference)(unsafe.Pointer(in.ParentRef))
	return nil
}

// Convert_networking_IPAddressSpec_To_v1alpha1_IPAddressSpec is an autogenerated conversion function.
func Convert_networking_IPAddressSpec_To_v1alpha1_IPAddressSpec(in *networking.IPAddressSpec, out *v1alpha1.IPAddressSpec, s conversion.Scope) error {
	return autoConvert_networking_IPAddressSpec_To_v1alpha1_IPAddressSpec(in, out, s)
}

func autoConvert_v1alpha1_ParametersRef_To_networking_ParametersRef(in *v1alpha1.ParametersRef, out *networking.ParametersRef, s conversion.Scope) error {
	out.Group = in.Group
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ParametersRef_To_networking_ParametersRef is an autogenerated conversion function.
func Convert_v1alpha1_ParametersRef_To_networking_ParametersRef(in *v1alpha1.ParametersRef, out *networking.ParametersRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_ParametersRef_To_networking_ParametersRef(in, out, s)
}

func autoConvert_networking_ParametersRef_To_v1alpha1_ParametersRef(in *networking.ParametersRef, out *v1alpha1.ParametersRef, s conversion.Scope) error {
	out.Group = in.Group
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_networking_ParametersRef_To_v1alpha1_ParametersRef is an autogenerated conversion function.
func Convert_networking_ParametersRef_To_v1alpha1_ParametersRef(in *networking.ParametersRef, out *v1alpha1.ParametersRef, s conversion.Scope) error {
	return autoConvert_networking_ParametersRef_To_v1alpha1_ParametersRef(in, out, s)
}

func autoConvert_v1alpha1_ParentReference_To_networking_ParentReference(in *v1alpha1.ParentReference, out *networking.ParentReference, s conversion.Scope) error {
	out.Group = in.Group
	out.Resource = in.Resource
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.UID = types.UID(in.UID)
	return nil
}

// Convert_v1alpha1_ParentReference_To_networking_ParentReference is an autogenerated conversion function.
func Convert_v1alpha1_ParentReference_To_networking_ParentReference(in *v1alpha1.ParentReference, out *networking.ParentReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ParentReference_To_networking_ParentReference(in, out, s)
}

func autoConvert_networking_ParentReference_To_v1alpha1_ParentReference(in *networking.ParentReference, out *v1alpha1.ParentReference, s conversion.Scope) error {
	out.Group = in.Group
	out.Resource = in.Resource
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.UID = types.UID(in.UID)
	return nil
}

// Convert_networking_ParentReference_To_v1alpha1_ParentReference is an autogenerated conversion function.
func Convert_networking_ParentReference_To_v1alpha1_ParentReference(in *networking.ParentReference, out *v1alpha1.ParentReference, s conversion.Scope) error {
	return autoConvert_networking_ParentReference_To_v1alpha1_ParentReference(in, out, s)
}

func autoConvert_v1alpha1_PodNetwork_To_networking_PodNetwork(in *v1alpha1.PodNetwork, out *networking.PodNetwork, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PodNetworkSpec_To_networking_PodNetworkSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PodNetworkStatus_To_networking_PodNetworkStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PodNetwork_To_networking_PodNetwork is an autogenerated conversion function.
func Convert_v1alpha1_PodNetwork_To_networking_PodNetwork(in *v1alpha1.PodNetwork, out *networking.PodNetwork, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodNetwork_To_networking_PodNetwork(in, out, s)
}

func autoConvert_networking_PodNetwork_To_v1alpha1_PodNetwork(in *networking.PodNetwork, out *v1alpha1.PodNetwork, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_networking_PodNetworkSpec_To_v1alpha1_PodNetworkSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_networking_PodNetworkStatus_To_v1alpha1_PodNetworkStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_networking_PodNetwork_To_v1alpha1_PodNetwork is an autogenerated conversion function.
func Convert_networking_PodNetwork_To_v1alpha1_PodNetwork(in *networking.PodNetwork, out *v1alpha1.PodNetwork, s conversion.Scope) error {
	return autoConvert_networking_PodNetwork_To_v1alpha1_PodNetwork(in, out, s)
}

func autoConvert_v1alpha1_PodNetworkAttachment_To_networking_PodNetworkAttachment(in *v1alpha1.PodNetworkAttachment, out *networking.PodNetworkAttachment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PodNetworkAttachmentSpec_To_networking_PodNetworkAttachmentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PodNetworkAttachmentStatus_To_networking_PodNetworkAttachmentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PodNetworkAttachment_To_networking_PodNetworkAttachment is an autogenerated conversion function.
func Convert_v1alpha1_PodNetworkAttachment_To_networking_PodNetworkAttachment(in *v1alpha1.PodNetworkAttachment, out *networking.PodNetworkAttachment, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodNetworkAttachment_To_networking_PodNetworkAttachment(in, out, s)
}

func autoConvert_networking_PodNetworkAttachment_To_v1alpha1_PodNetworkAttachment(in *networking.PodNetworkAttachment, out *v1alpha1.PodNetworkAttachment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_networking_PodNetworkAttachmentSpec_To_v1alpha1_PodNetworkAttachmentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_networking_PodNetworkAttachmentStatus_To_v1alpha1_PodNetworkAttachmentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_networking_PodNetworkAttachment_To_v1alpha1_PodNetworkAttachment is an autogenerated conversion function.
func Convert_networking_PodNetworkAttachment_To_v1alpha1_PodNetworkAttachment(in *networking.PodNetworkAttachment, out *v1alpha1.PodNetworkAttachment, s conversion.Scope) error {
	return autoConvert_networking_PodNetworkAttachment_To_v1alpha1_PodNetworkAttachment(in, out, s)
}

func autoConvert_v1alpha1_PodNetworkAttachmentList_To_networking_PodNetworkAttachmentList(in *v1alpha1.PodNetworkAttachmentList, out *networking.PodNetworkAttachmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]networking.PodNetworkAttachment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PodNetworkAttachmentList_To_networking_PodNetworkAttachmentList is an autogenerated conversion function.
func Convert_v1alpha1_PodNetworkAttachmentList_To_networking_PodNetworkAttachmentList(in *v1alpha1.PodNetworkAttachmentList, out *networking.PodNetworkAttachmentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodNetworkAttachmentList_To_networking_PodNetworkAttachmentList(in, out, s)
}

func autoConvert_networking_PodNetworkAttachmentList_To_v1alpha1_PodNetworkAttachmentList(in *networking.PodNetworkAttachmentList, out *v1alpha1.PodNetworkAttachmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.PodNetworkAttachment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_networking_PodNetworkAttachmentList_To_v1alpha1_PodNetworkAttachmentList is an autogenerated conversion function.
func Convert_networking_PodNetworkAttachmentList_To_v1alpha1_PodNetworkAttachmentList(in *networking.PodNetworkAttachmentList, out *v1alpha1.PodNetworkAttachmentList, s conversion.Scope) error {
	return autoConvert_networking_PodNetworkAttachmentList_To_v1alpha1_PodNetworkAttachmentList(in, out, s)
}

func autoConvert_v1alpha1_PodNetworkAttachmentSpec_To_networking_PodNetworkAttachmentSpec(in *v1alpha1.PodNetworkAttachmentSpec, out *networking.PodNetworkAttachmentSpec, s conversion.Scope) error {
	out.PodNetworkName = in.PodNetworkName
	out.ParametersRefs = *(*[]networking.ParametersRef)(unsafe.Pointer(&in.ParametersRefs))
	return nil
}

// Convert_v1alpha1_PodNetworkAttachmentSpec_To_networking_PodNetworkAttachmentSpec is an autogenerated conversion function.
func Convert_v1alpha1_PodNetworkAttachmentSpec_To_networking_PodNetworkAttachmentSpec(in *v1alpha1.PodNetworkAttachmentSpec, out *networking.PodNetworkAttachmentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodNetworkAttachmentSpec_To_networking_PodNetworkAttachmentSpec(in, out, s)
}

func autoConvert_networking_PodNetworkAttachmentSpec_To_v1alpha1_PodNetworkAttachmentSpec(in *networking.PodNetworkAttachmentSpec, out *v1alpha1.PodNetworkAttachmentSpec, s conversion.Scope) error {
	out.PodNetworkName = in.PodNetworkName
	out.ParametersRefs = *(*[]v1alpha1.ParametersRef)(unsafe.Pointer(&in.ParametersRefs))
	return nil
}

// Convert_networking_PodNetworkAttachmentSpec_To_v1alpha1_PodNetworkAttachmentSpec is an autogenerated conversion function.
func Convert_networking_PodNetworkAttachmentSpec_To_v1alpha1_PodNetworkAttachmentSpec(in *networking.PodNetworkAttachmentSpec, out *v1alpha1.PodNetworkAttachmentSpec, s conversion.Scope) error {
	return autoConvert_networking_PodNetworkAttachmentSpec_To_v1alpha1_PodNetworkAttachmentSpec(in, out, s)
}

func autoConvert_v1alpha1_PodNetworkAttachmentStatus_To_networking_PodNetworkAttachmentStatus(in *v1alpha1.PodNetworkAttachmentStatus, out *networking.PodNetworkAttachmentStatus, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_PodNetworkAttachmentStatus_To_networking_PodNetworkAttachmentStatus is an autogenerated conversion function.
func Convert_v1alpha1_PodNetworkAttachmentStatus_To_networking_PodNetworkAttachmentStatus(in *v1alpha1.PodNetworkAttachmentStatus, out *networking.PodNetworkAttachmentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodNetworkAttachmentStatus_To_networking_PodNetworkAttachmentStatus(in, out, s)
}

func autoConvert_networking_PodNetworkAttachmentStatus_To_v1alpha1_PodNetworkAttachmentStatus(in *networking.PodNetworkAttachmentStatus, out *v1alpha1.PodNetworkAttachmentStatus, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_networking_PodNetworkAttachmentStatus_To_v1alpha1_PodNetworkAttachmentStatus is an autogenerated conversion function.
func Convert_networking_PodNetworkAttachmentStatus_To_v1alpha1_PodNetworkAttachmentStatus(in *networking.PodNetworkAttachmentStatus, out *v1alpha1.PodNetworkAttachmentStatus, s conversion.Scope) error {
	return autoConvert_networking_PodNetworkAttachmentStatus_To_v1alpha1_PodNetworkAttachmentStatus(in, out, s)
}

func autoConvert_v1alpha1_PodNetworkList_To_networking_PodNetworkList(in *v1alpha1.PodNetworkList, out *networking.PodNetworkList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]networking.PodNetwork)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PodNetworkList_To_networking_PodNetworkList is an autogenerated conversion function.
func Convert_v1alpha1_PodNetworkList_To_networking_PodNetworkList(in *v1alpha1.PodNetworkList, out *networking.PodNetworkList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodNetworkList_To_networking_PodNetworkList(in, out, s)
}

func autoConvert_networking_PodNetworkList_To_v1alpha1_PodNetworkList(in *networking.PodNetworkList, out *v1alpha1.PodNetworkList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.PodNetwork)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_networking_PodNetworkList_To_v1alpha1_PodNetworkList is an autogenerated conversion function.
func Convert_networking_PodNetworkList_To_v1alpha1_PodNetworkList(in *networking.PodNetworkList, out *v1alpha1.PodNetworkList, s conversion.Scope) error {
	return autoConvert_networking_PodNetworkList_To_v1alpha1_PodNetworkList(in, out, s)
}

func autoConvert_v1alpha1_PodNetworkSpec_To_networking_PodNetworkSpec(in *v1alpha1.PodNetworkSpec, out *networking.PodNetworkSpec, s conversion.Scope) error {
	out.IPAM4 = (*networking.IPAMType)(unsafe.Pointer(in.IPAM4))
	out.IPAM6 = (*networking.IPAMType)(unsafe.Pointer(in.IPAM6))
	out.ParametersRefs = *(*[]networking.ParametersRef)(unsafe.Pointer(&in.ParametersRefs))
	out.Provider = in.Provider
	return nil
}

// Convert_v1alpha1_PodNetworkSpec_To_networking_PodNetworkSpec is an autogenerated conversion function.
func Convert_v1alpha1_PodNetworkSpec_To_networking_PodNetworkSpec(in *v1alpha1.PodNetworkSpec, out *networking.PodNetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodNetworkSpec_To_networking_PodNetworkSpec(in, out, s)
}

func autoConvert_networking_PodNetworkSpec_To_v1alpha1_PodNetworkSpec(in *networking.PodNetworkSpec, out *v1alpha1.PodNetworkSpec, s conversion.Scope) error {
	out.IPAM4 = (*v1alpha1.IPAMType)(unsafe.Pointer(in.IPAM4))
	out.IPAM6 = (*v1alpha1.IPAMType)(unsafe.Pointer(in.IPAM6))
	out.ParametersRefs = *(*[]v1alpha1.ParametersRef)(unsafe.Pointer(&in.ParametersRefs))
	out.Provider = in.Provider
	return nil
}

// Convert_networking_PodNetworkSpec_To_v1alpha1_PodNetworkSpec is an autogenerated conversion function.
func Convert_networking_PodNetworkSpec_To_v1alpha1_PodNetworkSpec(in *networking.PodNetworkSpec, out *v1alpha1.PodNetworkSpec, s conversion.Scope) error {
	return autoConvert_networking_PodNetworkSpec_To_v1alpha1_PodNetworkSpec(in, out, s)
}

func autoConvert_v1alpha1_PodNetworkStatus_To_networking_PodNetworkStatus(in *v1alpha1.PodNetworkStatus, out *networking.PodNetworkStatus, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_PodNetworkStatus_To_networking_PodNetworkStatus is an autogenerated conversion function.
func Convert_v1alpha1_PodNetworkStatus_To_networking_PodNetworkStatus(in *v1alpha1.PodNetworkStatus, out *networking.PodNetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PodNetworkStatus_To_networking_PodNetworkStatus(in, out, s)
}

func autoConvert_networking_PodNetworkStatus_To_v1alpha1_PodNetworkStatus(in *networking.PodNetworkStatus, out *v1alpha1.PodNetworkStatus, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_networking_PodNetworkStatus_To_v1alpha1_PodNetworkStatus is an autogenerated conversion function.
func Convert_networking_PodNetworkStatus_To_v1alpha1_PodNetworkStatus(in *networking.PodNetworkStatus, out *v1alpha1.PodNetworkStatus, s conversion.Scope) error {
	return autoConvert_networking_PodNetworkStatus_To_v1alpha1_PodNetworkStatus(in, out, s)
}
